spring.application.name=simpleecommerceapp


spring.datasource.url=jdbc:postgresql://dpg-dabbniss728c73a7os3g-a.oregon-postgres.render.com:5432/ecommerce_site
spring.datasource.username=ecommerce_site_user
spring.datasource.password=uFgTXFbHKw10zLEpaucloN7EKXQt43Ij
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
#postgresql://ecommerce_site_user:uFgTXFbHKw10zLEpaucloN7EKXQt43Ij@dpg-dabbniss728c73a7os3g-a.oregon-postgres.render.com/ecommerce_site